base: &BASE
    
    # Hyperparameters
    learn_rate: 2E-4
    noise_vect: 64
    batchsize: 64
    Nconvfilters: [64, 128, 256, 512]
    Ndeconvfilters: [256, 128, 64, 1]
    dataname: '/global/project/projectdirs/dasrepo/vpa/cosmogan/data/raw_data/'
    checkpoint_prefix: 'ckpt'
    
    # Loss weight terms -- can set any of these to 0 to test different combinations
    # of spectral constraint loss, feature matching loss, and R1 regularization.
    # Surprisingly, so far the most effective configuration seems to be just setting all
    # weights to 1.
    LAMBDA_1: 1. # weight term for the spectral constraint on the mean P(k) per k bin
    LAMBDA_2: 1. # weight term for the spectral constraint on the variance of P(k) per k bin
    LAMBDA_3: 1. # weight term for the feature matching loss
    R_LAMBDA: 1. # R1 regularization weight
    
    # Load the target P(k) distribution: mean and variance per k bin over training set
    tar_Pk_file: 'data/Pk_mean_real.npy'
    tar_Pk_std_file: 'data/Pk_std_real.npy'
    